// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idrizzffwnujhbmkwqys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlkcml6emZmd251amhibWt3cXlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MTk5MDIsImV4cCI6MjA2NTI5NTkwMn0.Y2gyzecmWrFqeVYLriWfibV-GQL0vWSK3HRnM7s1De8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);